### ISSUE TITLE
McAfee EPO analysis doesn't cover x64

### ISSUE THREAD

**Issue by mbrownr** [strawgate/C3-Protect#10]
Use this:
values "DisplayVersion" of keys whose (value "DisplayName" of it as string is "McAfee Agent") of keys "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall" of (x32 registry; (if exists x64 registry then x64 registry else nothing))

**Comment by strawgate** [comment]
This appears to have been resolved.
