### ISSUE TITLE
Deploy - EMET - 5.51 does not check EMET version

### ISSUE THREAD

**Issue by Jwalker107** [strawgate/C3-Protect#17]
The Relevance on "Deploy - EMET - 5.51" at https://bigfix.me/fixlet/details/21265 does not check for the version number of an existing EMET.  The presence of EMET 5.5 (or earlier) will cause EMET 5.51  to be non-relevant. 

Recommend Relevance change to add a check for "DisplayVersion" registry key

From:

(windows of operating system) and (version of operating system >= "6.1") and (exists key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0" of registry) and (if exists property "in proxy agent context" then ( not in proxy agent context ) else true) and (free space of drive of client > 26808320 \* 2) and (not exists (key of keys "HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall" of ( x32 registry; (if exists x64 registry then x64 registry else nothing) )) whose (value "DisplayName" of it as string starts with "EMET"))

To:

(windows of operating system) and (version of operating system >= "6.1") and (exists key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0" of registry) and (if exists property "in proxy agent context" then ( not in proxy agent context ) else true) and (free space of drive of client > 26808320 \* 2) and (not exists (key of keys "HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall" of ( x32 registry; (if exists x64 registry then x64 registry else nothing) )) whose (value "DisplayName" of it as string starts with "EMET" and value "DisplayVersion" of it as string as version >= version "5.51"))

EMET 5.51 reports DisplayVersion 5.51 in the Registry.
EMET 5.5 reports DisplayVersion 5.5
I haven't checked with any earlier EMET versions.

**Comment by strawgate** [comment]
Jason,

I'm working on getting a c3 patch repo up but it's not quite ready yet.

For this particular issue it would be helpful for me to provide some documentation regarding the fixlets in the patch site.

For each app we generate three fixlets:
Deploy
Update
Uninstall

Deploy will only be relevant on machines that do not have any version of the software installed.
Update will only be relevant on machines that do have the software installed but are of an old version.
Uninstall will only be relevant on machines that have the software installed.

Let me know if this doesn't make sense and I'll let you know when the patch repo is up!
Bill

**Comment by Jwalker107** [comment]
That makes complete sense.  Sorry for my confusion.
