### ISSUE TITLE
Copy/paste bug in Firewall - State - Windows property

### ISSUE THREAD

**Issue by seanjseymour** [strawgate/C3-Protect#28]
Unless I am missing something, it appears that the **Firewall - State - Windows** property has a copy/paste issue. I believe the Public section should be looking at the HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsFirewall\\**PublicProfile** registry key, however it is looking at **StandardProfile** instead.

**Comment by strawgate** [comment]
Thanks for the report! I'll have a new version up momentarily.
